version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    restart: always
    # environment:
    #   POSTGRES_USER: your_user
    #   POSTGRES_PASSWORD: your_password
    #   POSTGRES_DB: your_db
    env_file:
      - stack.env
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgresql.conf:/usr/local/etc/postgresql/postgresql.conf
    command: -c 'config_file=/usr/local/etc/postgresql/postgresql.conf'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
